/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    About: typeof import('./components/pages/About.vue')['default']
    AboutTemplate: typeof import('./components/templates/AboutTemplate.vue')['default']
    AboutUs: typeof import('./components/pages/AboutUs.vue')['default']
    AppHome: typeof import('./components/pages/AppHome.vue')['default']
    AppToaster: typeof import('./components/molecules/AppToaster.vue')['default']
    Button: typeof import('./components/atoms/Button.vue')['default']
    Card: typeof import('./components/molecules/Card.vue')['default']
    CustomCard: typeof import('./components/CustomCard.vue')['default']
    DsfrAlert: typeof import('@gouvminint/vue-dsfr')['DsfrAlert']
    DsfrButton: typeof import('@gouvminint/vue-dsfr')['DsfrButton']
    DsfrFooter: typeof import('@gouvminint/vue-dsfr')['DsfrFooter']
    DsfrHeader: typeof import('@gouvminint/vue-dsfr')['DsfrHeader']
    Footer: typeof import('./components/organisms/Footer.vue')['default']
    Header: typeof import('./components/organisms/Header.vue')['default']
    Home: typeof import('./components/pages/Home.vue')['default']
    HomeTemplate: typeof import('./components/templates/HomeTemplate.vue')['default']
    Input: typeof import('./components/atoms/Input.vue')['default']
    ReloadPrompt: typeof import('./components/molecules/ReloadPrompt.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SearchBar: typeof import('./components/molecules/SearchBar.vue')['default']
    VIcon: typeof import('@gouvminint/vue-dsfr')['VIcon']
  }
}
